create database if not exists s_students;
use s_students;
create table class1_students(student_id int auto_increment primary key,
								student_name varchar(100),
                                gender enum('male','female'),
                                age int);
create table class2_students(student_id int auto_increment primary key,
								student_name varchar(100),
                                gender enum('male','female'),
                                age int);
create table class3_students(student_id int auto_increment primary key,
								student_name varchar(100),
                                gender enum('male','female'),
                                age int);						
create table class4_students(student_id int auto_increment primary key,
								student_name varchar(100),
                                gender enum('male','female'),
                                age int) ;                               
create table class5_students(student_id int auto_increment primary key,
								student_name varchar(100),
                                gender enum('male','female'),
                                age int);
 insert into class1_students (student_name, gender, age) values
('Aarav Kumar', 'male', 6),
('Ishika Sharma', 'female', 6),
('Rohan Patel', 'male', 7),
('Meera Singh', 'female', 6),
('Karthik Reddy', 'male', 7),
('Anaya Das', 'female', 6),
('Vihaan Nair', 'male', 6),
('Saanvi Gupta', 'female', 7),
('Advik Rao', 'male', 6),
('Diya Mehta', 'female', 6),
('Arjun Verma', 'male', 7),
('Aadhya Iyer', 'female', 6),
('Reyansh Nanda', 'male', 7),
('Kiara Pillai', 'female', 6),
('Krishna Sharma', 'male', 6),
('Avni Singh', 'female', 7),
('Dhruv Reddy', 'male', 7),
('Myra Paul', 'female', 6),
('Ritvik Joshi', 'male', 6),
('Pari Menon', 'female', 7);
insert into class2_students (student_name, gender, age) values
('Aarav Nair', 'male', 7),
('Aadhya Gupta', 'female', 7),
('Ritvik Joshi', 'male', 8),
('Kiara Mehta', 'female', 7),
('Aditya Rao', 'male', 8),
('Saanvi Iyer', 'female', 7),
('Rohan Verma', 'male', 7),
('Meera Das', 'female', 7),
('Krish Patel', 'male', 8),
('Anaya Sharma', 'female', 7),
('Vivaan Singh', 'male', 8),
('Navya Pillai', 'female', 7),
('Reyansh Das', 'male', 7),
('Ira Menon', 'female', 8),
('Kavin Nair', 'male', 7),
('Avni Gupta', 'female', 8),
('Aarush Reddy', 'male', 8),
('Misha Iyer', 'female', 7),
('Laksh Verma', 'male', 8),
('Sara Paul', 'female', 7);
insert into  class3_students (student_name, gender, age) values
('Aryan Sharma', 'male', 8),
('Diya Patel', 'female', 8),
('Reyansh Verma', 'male', 9),
('Avni Choudhary', 'female', 8),
('Kabir Das', 'male', 9),
('Myra Reddy', 'female', 8),
('Aarush Gupta', 'male', 8),
('Kiara Menon', 'female', 8),
('Dev Iyer', 'male', 9),
('Sia Paul', 'female', 8),
('Rohan Rao', 'male', 9),
('Pari Sharma', 'female', 8),
('Hriday Mehta', 'male', 9),
('Navya Das', 'female', 8),
('Krishna Nair', 'male', 8),
('Anaya Singh', 'female', 8),
('Arjun Patel', 'male', 9),
('Mira Verma', 'female', 9),
('Ishaan Joshi', 'male', 8),
('Aanya Reddy', 'female', 9);
insert into  class4_students (student_name, gender, age) values
('Vivaan Shetty', 'male', 9),
('Ira Nair', 'female', 9),
('Rudra Singh', 'male', 10),
('Navya Gupta', 'female', 9),
('Krishna Menon', 'male', 10),
('Sara Paul', 'female', 9),
('Aditya Das', 'male', 10),
('Aadhya Sharma', 'female', 9),
('Rohan Nair', 'male', 10),
('Kiara Iyer', 'female', 9),
('Kabir Patel', 'male', 10),
('Myra Reddy', 'female', 9),
('Aryan Mehta', 'male', 9),
('Diya Verma', 'female', 10),
('Laksh Singh', 'male', 10),
('Avni Das', 'female', 9),
('Aarav Gupta', 'male', 9),
('Saanvi Rao', 'female', 9),
('Karthik Pillai', 'male', 10),
('Anaya Menon', 'female', 9);
insert into class5_students (student_name, gender, age) values
('Arjun Das', 'male', 10),
('Pari Sharma', 'female', 10),
('Dev Patel', 'male', 11),
('Ananya Rao', 'female', 10),
('Hriday Iyer', 'male', 11),
('Misha Nair', 'female', 10),
('Ritvik Menon', 'male', 11),
('Kiara Paul', 'female', 10),
('Kavin Reddy', 'male', 10),
('Avni Singh', 'female', 11),
('Aryan Gupta', 'male', 10),
('Diya Verma', 'female', 11),
('Krishna Das', 'male', 11),
('Navya Mehta', 'female', 10),
('Aarav Nair', 'male', 11),
('Sia Pillai', 'female', 10),
('Vivaan Sharma', 'male', 11),
('Anaya Joshi', 'female', 10),
('Rohan Rao', 'male', 11),
('Aadhya Iyer', 'female', 10);
                               